doctors/urls.py
from django.urls import path

from . import views


app_name = "doctors"


urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("doctors/<slug:slug>/", views.DoctorDetailView.as_view(), name="detail"),
    path(
        "doctors/<slug:slug>/appointment/",
        views.create_appointment,
        name="create_appointment",
    ),
    path(
        "appointments/<int:appointment_id>/cancel/",
        views.cancel_appointment,
        name="cancel_appointment",
    ),
    path("profile/<int:user_id>/", views.profile, name="profile"),
    path("edit-profile/", views.EditProfileView.as_view(), name="edit_profile"),
]

hospital/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from doctors import views
from django.conf import settings

urlpatterns = [
    path('', include('doctors.urls')),
    path('pages/', include('pages.urls')),

    path('admin/', admin.site.urls),

    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        views.RegisterView.as_view(),
        name='registration'
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.page_internal_server_error'

pages/urls.py
from django.urls import path

from . import views


app_name = 'pages'

urlpatterns = [
    path('about/', views.About.as_view(), name='about'),
    path('rules/', views.Rules.as_view(), name='rules'),
    
]

templates/pages/403csrf.html
{% extends "base.html" %}
{% block title %}Ошибка CSRF токена{% endblock %}
{% block content %}
  <h1>Ошибка CSRF токена. 403</h1>
  <a href="{% url 'doctors:index' %}">Вернуться на главную</a>
{% endblock %}

templates/pages/about.html
{% extends "base.html" %}
{% block title %}
  О городской больнице
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        <strong>О больнице</strong>
      </div>
      <div class="card-body">
        <p>
          Наша больница была основана с целью предоставления высококачественной медицинской помощи всем членам нашего сообщества.
          Мы гордимся тем, что являемся важной частью системы здравоохранения и стремимся обеспечить доступ к
          медицинским услугам для каждого пациента.
        </p>
        <p>
          В нашей больнице работают терапевты и узкие специалисты, готовые принять вас в удобное время.
          Мы стремимся сделать процесс записи на приём максимально простым и доступным,
          а пребывание в больнице — комфортным.
        </p>
        <p>
          Мы стремимся к тому, чтобы каждый пациент получал заботу, основанную на уважении, достоинстве и профессионализме.
          На сайте вы можете ознакомиться с расписанием работы врачей,
          узнать о доступных специалистах и записаться на приём онлайн. Мы ценим ваше время и здоровье!
        </p>
        <p>
          <strong>Наша миссия</strong> -  обеспечивать высококачественное медицинское обслуживание,
          способствующее улучшению здоровья и благополучия населения.
          Мы постоянно совершенствуем свои навыки и внедряем новые технологии, чтобы оказывать медицинскую помощь на самом высоком уровне.
        </p>
      </div>
    </div>
  </div>
{% endblock %}

templates/pages/rules.html
{% extends "base.html" %}
{% block title %}
  Наши правила
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Правила сайта
      </div>
      <div class="card-body">
        <p>
          <b>Cамовыражение.</b> У наших пользователей должна
          быть возможность создать что-то своё, выразить себя,
          свои мысли и чувства.
        </p>
        <p>
          <b>Многообразие.</b> Мы уважаем и приветствуем разные
          мнения и культуры. Блогикум — это место, объединяющее
          самых разных людей. Поделитесь своим уникальным взглядом на мир.
        </p>
        <p>
          <b>Творчество.</b> Не важно, в какой области вы творите,
          это может быть литература, дизайн, программирование.
          Наши инструменты помогут вам раскрыть талант максимально
          просто и комфортно.
        </p>
        <p>
          <b>Личность.</b> Мы сохраним ваши сокровенные мысли в тайне.
          Делитесь своей информацией только с теми, кого выбрали.
          Как и насколько засекречивать вашу личную информацию —
          определяете вы и только вы.
        </p>
      </div>
    </div>
  </div>
{% endblock %}